// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBqBeL1F2g4hrEvHcxB0YCyeVouOZgrQQ',
    appId: '1:123116185092:web:db94887f0a9308a8213751',
    messagingSenderId: '123116185092',
    projectId: 'flutter-projects-97a4e',
    authDomain: 'flutter-projects-97a4e.firebaseapp.com',
    storageBucket: 'flutter-projects-97a4e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk3UxBtmezqTbA9b1bffypMJPG-hTcafg',
    appId: '1:123116185092:android:5f9252e7d0050ffb213751',
    messagingSenderId: '123116185092',
    projectId: 'flutter-projects-97a4e',
    storageBucket: 'flutter-projects-97a4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAljPwgHGOzq61pE4F8gF6EjV1qZTDeQ3Y',
    appId: '1:123116185092:ios:7379d9ab19552823213751',
    messagingSenderId: '123116185092',
    projectId: 'flutter-projects-97a4e',
    storageBucket: 'flutter-projects-97a4e.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAljPwgHGOzq61pE4F8gF6EjV1qZTDeQ3Y',
    appId: '1:123116185092:ios:7379d9ab19552823213751',
    messagingSenderId: '123116185092',
    projectId: 'flutter-projects-97a4e',
    storageBucket: 'flutter-projects-97a4e.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBqBeL1F2g4hrEvHcxB0YCyeVouOZgrQQ',
    appId: '1:123116185092:web:00c0967216807f9f213751',
    messagingSenderId: '123116185092',
    projectId: 'flutter-projects-97a4e',
    authDomain: 'flutter-projects-97a4e.firebaseapp.com',
    storageBucket: 'flutter-projects-97a4e.appspot.com',
  );
}
